[build]
  base = ""
  command = "npm install --legacy-peer-deps --no-optional && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[context.production.environment]
  BUILD_IMAGE = "focal"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
