// 사격 개념서형 샘플의 "현장의 목소리"와 장별 현장 팁.
// 근거: research-community.md, research-creators.md (2026-10-10 조사).
// 디스코드 본문은 로그인이 필요해 읽지 않았다. 12.1.5 PTR 자료는 라이브 운용과 섞지 않는다.
// 스킬 이름은 KB 공식 한국어 이름으로 옮겼다. 원문 인용은 voices.takeaways에만 짧게 둔다.

const VOICES = [
  {
    id: 'trueshot',
    name: 'Trueshot Lodge',
    channel: '직업 디스코드',
    title: 'Trueshot Lodge 사냥꾼 디스코드 공개 초대',
    url: 'https://discord.com/invite/trueshot',
    date: '2026-10-10 확인 · 회원 약 10만 8천 명',
    access: '공개 초대 정보만 확인(본문은 로그인 필요)',
    takeaways: [
      '사냥꾼 공식 직업 디스코드입니다. 운영 책임자인 Azortharion이 Icy Veins·Wowhead 사격 가이드와 SimC 사격 딜사이클을 함께 관리합니다.',
      '디스코드 대화는 읽지 않았습니다. 대신 운영진이 공개한 가이드·시뮬레이션·영상을 아래 카드로 모았습니다.',
    ],
  },
  {
    id: 'azortharion-iv',
    name: 'Azortharion',
    channel: '가이드 글 · Icy Veins',
    title: '사격 딜사이클·쿨기 가이드 외 특성·쐐기 팁·매크로·쉬운 운용(Icy Veins)',
    url: 'https://www.icy-veins.com/wow/marksmanship-hunter-pve-dps-rotation-cooldowns-abilities',
    date: '2026-08-31 수정(12.1 반영 2026-08-10)',
    access: '직접 읽음',
    takeaways: [
      '영웅 특성은 모든 콘텐츠에서 파수꾼, 예외 없음이라고 적습니다.',
      '정조준은 속사 바로 앞에 쓰고, 폭발 사격이 곧 돌아오면 최대 15초까지 미룹니다. 마지막 정조준은 명중 30중첩에 맞춥니다.',
      '8월 22일부터 속사 끝을 끊는 운용은 파수꾼 광역에서만 합니다.',
      '1초 고민하느니 틀린 주문이라도 바로 쓰는 편이 낫다며 빈 글쿨을 가장 큰 실수로 꼽습니다.',
    ],
  },
  {
    id: 'azortharion-wh',
    name: 'Azortharion',
    channel: '가이드 글 · Wowhead',
    title: 'Wowhead 사격 딜사이클·쐐기·레이드 팁',
    url: 'https://www.wowhead.com/ko/guide/classes/hunter/marksmanship/rotation-cooldowns-pve-dps',
    date: '2026-08-18~08-24 수정',
    access: '직접 읽음(브라우저)',
    takeaways: [
      '조준 사격을 시전하지 않으면서 가만히 서 있는 것은 거의 최선이 아니라고 말합니다. 이동은 조준 사격을 쏘지 않는 시간에 모읍니다.',
      '쐐기에서는 광역 대상 수에 상한이 있고 정조준 사이 피해가 낮아, 쿨기 실수의 대가가 크다고 봅니다.',
      '맹독 심연 레이드는 대부분 히드라의 상 빌드, 단일 우두머리와 광역 우두머리만 빌드를 바꿉니다.',
    ],
  },
  {
    id: 'azortharion-sims',
    name: 'Azortharion',
    channel: '이론가 시뮬레이션',
    title: '12.1 사냥꾼 시뮬레이션(Patch 12.1 Hunter Sims)',
    url: 'https://azortharion.com/hunter-sims/',
    date: '2026-09-19 갱신 · 2026-09-30 재계산',
    access: '직접 읽음',
    takeaways: [
      '공격대 단일: 파수꾼 246.7K, 어둠 순찰자 220.5K. 쐐기 경로: 437.6K 대 416.6K. 최상급 장비를 가정한 시뮬레이션 수치입니다.',
      '유동성 제동장치와 전술 재장전은 파수꾼에서 단일·쐐기 모두 사실상 같습니다.',
      '쐐기에서 교묘한 사격 대신 히드라의 상을 쓰면 파수꾼 기준 약 13.6% 손해입니다.',
    ],
  },
  {
    id: 'azortharion-videos',
    name: 'Azortharion',
    channel: '영상 · 레이드 시점 해설',
    title: '쌍둥이 송곳니 1위 사격 시점 해설 외 4편(TWIN FANGS | Rank 1 MM Hunter PoV)',
    url: 'https://www.youtube.com/watch?v=lSh9qaa-nrA',
    date: '2026-08-25~10-01 게시',
    access: '공개 자동 자막 읽음(울라텍 신화편은 발췌)',
    takeaways: [
      '끝까지 시전할 자신이 없는 조준 사격은 절대 시작하지 말라고 거듭 말합니다.',
      '우두머리가 사라지기 직전에는 속사를 시작하지 않고, 다시 나타나면 조준 사격부터 씁니다.',
      '연사로 붙는 폭발 사격은 연발 공격 0.5초 뒤에 걸리니, 졸개가 나오기 직전에 깔아도 됩니다.',
      '거북의 상은 미리 계획해 쓰고 바로 취소해 공격으로 돌아옵니다. 불굴을 뺐다가 두세 번 더 죽었다고 스스로 말합니다.',
    ],
  },
  {
    id: 'qenjua',
    name: 'Qenjua',
    channel: '가이드 글 · Method',
    title: '사격 운용과 딜사이클(Playstyle and Rotation)',
    url: 'https://www.method.gg/guides/marksmanship-hunter/playstyle-and-rotation',
    date: '2026-09-05 수정',
    access: '직접 읽음',
    takeaways: [
      '조준 사격은 절대 2회 충전에 닿으면 안 된다고 적습니다. 두 충전 방치부터 막습니다.',
      '이동 때문에 조준 사격을 취소했다면 이동하면서 신비한 사격이나 고정 사격을 씁니다.',
      '페이지 아래쪽 일부 문장은 8월 20일 수정 이전 내용이 남아 있어 따르지 않았습니다.',
    ],
  },
  {
    id: 'bansherz',
    name: 'Bansherz',
    channel: '영상 · 고단 쐐기 사냥꾼',
    title: '시즌 2 사격 특성과 딜사이클(MM Hunter Guide Talents & Rotation)',
    url: 'https://www.youtube.com/watch?v=foRnDiuAC7E',
    date: '2026-08-11 게시 · 10분 50초',
    access: '공개 자동 자막 전체',
    takeaways: [
      '지금 어둠 순찰자는 너무 뒤처져 있다며 쓰지 않습니다.',
      '쐐기에서는 사격 지휘(정조준 1분 30초)를 선호하고, 졸개가 나오는 주기에 따라 고르라고 합니다.',
    ],
  },
  {
    id: 'awoo',
    name: 'Awoo · Bansherz 출연',
    channel: '영상 · 사냥꾼 종합',
    title: '시즌 2 사냥꾼 세 전문화 종합(Complete Hunter Guide)',
    url: 'https://www.youtube.com/watch?v=LSKkSnwBtbs',
    date: '2026-08-19 게시 · 사격 구간 5분 19초~11분 24초',
    access: '공개 자동 자막(사격 구간 전체)',
    takeaways: [
      '광역은 결국 조준 사격, 일제 사격, 속사, 일제 사격의 반복이라고 설명합니다.',
      '조준 사격과 속사가 둘 다 준비돼 있으면 속사부터, 연발 공격 6초 안에 속사와 조준 사격을 빨리 넣습니다.',
    ],
  },
  {
    id: 'eggplant',
    name: 'Mr. Eggplant',
    channel: '영상 · 사격 가이드',
    title: '12.1 사격 가이드(12.1 MM Hunter Guide)',
    url: 'https://www.youtube.com/watch?v=dJv1Hqmgq4Y',
    date: '2026-08-18 게시 · 22분 28초',
    access: '공개 자동 자막 전체',
    takeaways: [
      '정조준 구간에는 폭발 사격을 넣을 시간이 보통 없으니 정조준 앞에 쓰라고 합니다.',
      '파수꾼은 반응할 발동이 없어 매끄럽고, 어둠 순찰자 광역은 반응형이라 처음엔 어색하다고 평가합니다.',
      '처음 배우거나 복귀했다면 전술 재장전이 흐름이 매끄럽다고 권합니다.',
    ],
  },
  {
    id: 'reddit-logs',
    name: 'r/CompetitiveWoW 로그 진단 글',
    channel: '커뮤니티 · Reddit',
    title: '사격 로그 진단 요청과 답변(From MM to BM)',
    url: 'https://www.reddit.com/r/CompetitiveWoW/comments/1wbrqkk/from_mm_to_bm/',
    date: '2026-09-09~09-13',
    access: '직접 읽음(추천 많은 답변 위주)',
    takeaways: [
      '조준 사격과 신비한 사격의 시전 수는 늘 같아야 한다는 답변입니다. 조준 사격 직후 신비한 사격 한 번이 기본입니다.',
      '정조준 직후 손을 놓는 것, 취소된 조준 사격이 많은 것을 가장 큰 손실로 지적합니다.',
    ],
  },
  {
    id: 'reddit-dps',
    name: 'r/wow 쐐기 피해량 상담 글',
    channel: '커뮤니티 · Reddit',
    title: '상위 100위 로그와 비교한 답변(DPS Problem)',
    url: 'https://www.reddit.com/r/wow/comments/1wzcwv9/dps_problem/',
    date: '2026-10-06',
    access: '직접 읽음',
    takeaways: [
      '질문자의 시전 상위는 신비한 사격·고정 사격·조준 사격, 상위 100위 로그는 일제 사격·조준 사격·속사였습니다.',
      '일제 사격을 훨씬 더 많이 써야 한다는 답변입니다. 쐐기에서는 일제 사격이 시전 상위에 와야 합니다.',
    ],
  },
  {
    id: 'reddit-nalorakk',
    name: 'r/CompetitiveWoW 평정의 사격 질문 글',
    channel: '커뮤니티 · Reddit',
    title: 'Den of Nalorakk 격노한 곰에게 평정의 사격을 언제 쓰나',
    url: 'https://www.reddit.com/r/CompetitiveWoW/comments/1vtpckk/den_of_nalorakk_enraging_bears_when_am_i_suppose/',
    date: '2026-08-20~08-30',
    access: '직접 읽음',
    takeaways: [
      '어미 곰의 격노는 새끼가 모두 죽은 뒤에 지우라는 답변이 가장 많은 추천을 받았습니다.',
      '평정의 사격이 이제 중첩을 모두 지운다는 제보는 패치 노트에 없어 확인되지 않았습니다.',
    ],
  },
  {
    id: 'forum-unload',
    name: 'Takumaru 외',
    channel: '공식 포럼 · 사냥꾼 게시판',
    title: '쏟아내기 삭제 토론(Unload Removed)',
    url: 'https://us.forums.blizzard.com/en/wow/t/unload-removed/2344932',
    date: '2026-09-05',
    access: '직접 읽음',
    takeaways: [
      '단일 대상에서는 속사 정신 집중을 전혀 끊지 않는다고 설명합니다.',
      '12.1.5 테스트 서버(PTR)에서 쏟아내기 삭제가 예고돼 있어, 그 패치가 오면 속사 운용이 다시 바뀝니다.',
    ],
  },
  {
    id: 'stats',
    name: 'Archon · murlok.io',
    channel: '집계',
    title: 'Archon 신화 공격대·쐐기 상위 키, murlok.io 쐐기 상위 50명',
    url: 'https://www.archon.gg/wow/builds/marksmanship/hunter/raid/talents/mythic/all-bosses',
    date: '2026-10-10 조회',
    access: '브라우저로 집계 화면만 읽음',
    takeaways: [
      '파수꾼 선택 비율: 신화 레이드 99.9%(18,313건), 쐐기 상위 키 97.8%(1,336건), murlok 쐐기 상위 50명 중 49명.',
      '사용 비율이지 같은 조건의 성능 비교는 아닙니다. 조정 전후 기록이 섞여 있을 수 있습니다.',
    ],
  },
  {
    id: 'kr-geumchip',
    name: '금칩',
    channel: '한국 영상',
    title: '12.1.0. 격냥 딜사이클 가이드 / 딜사이클 가이드 A/S',
    url: 'https://www.youtube.com/watch?v=cFIoPWZehck',
    date: '2026-08-26 · A/S편 2026-09-02',
    access: '제목·설명·챕터만 확인(자막 접근 차단)',
    takeaways: [
      'A/S편 설명란: 쏟아내기 수정 뒤 단일 순서를 "조준 사격 → 속사 → 조준 사격"으로 간소화했다고 적었습니다.',
      '영상 본문은 확인하지 못해 장별 팁의 근거로 쓰지 않았습니다.',
    ],
  },
  {
    id: 'kr-inven',
    name: '인벤 사냥꾼 게시판',
    channel: '한국 커뮤니티',
    title: '격냥 딜사이클에 대하여 외 12.1 격냥 글',
    url: 'https://www.inven.co.kr/board/wow/49/190224',
    date: '2026-08-20~10-07',
    access: '본문 직접 읽음(댓글 미확인)',
    takeaways: [
      '상위권 로그는 속사를 쿨다운마다 쓰고 조준 사격 뒤에는 신비한 사격·일제 사격·마무리 사격으로 소비한다는 정리가 있습니다.',
      '야수에서 넘어온 이용자가 로그를 보니 쿨기와 주요 스킬을 제때 못 쓴 것이 가장 큰 손실이었다는 사례가 있습니다.',
      '표식 돌리기가 너무 어렵다는 질문이 여러 번 올라왔습니다.',
    ],
  },
];

const FIELD_TIPS = {
  core: [
    { voice: 'azortharion-iv', text: '1초 고민하고 맞는 스킬을 쓰는 것보다 틀린 스킬이라도 바로 쓰는 편이 낫습니다. 좋은 사냥꾼도 가장 많이 하는 실수가 빈 글쿨입니다.' },
    { voice: 'qenjua', text: '조준 사격은 두 충전에 닿지 않게 둡니다. 두 칸이 찼다면 그 순간이 가장 먼저 고칠 손실입니다.' },
  ],
  precise: [
    { voice: 'reddit-logs', text: '조준 사격이 끝나기 전에 정밀 사격 소비를 미리 입력해 바로 이어 붙입니다. 로그에서 조준 사격과 신비한 사격 시전 수가 거의 같으면 리듬이 맞은 것입니다.' },
    { voice: 'azortharion-iv', text: '조준 사격 바로 다음이 속사라면 사이에 정밀 사격 소비를 넣지 않아도 됩니다. 쏟아내기가 속사 시작에 신비한 사격을 자동으로 쏴 정밀 사격을 가져갑니다.' },
  ],
  rapidfire: [
    { voice: 'awoo', text: '조준 사격과 속사가 둘 다 준비돼 있으면 속사부터 씁니다. 속사가 조준 사격 충전을 당겨 주니 다음 조준 사격이 더 빨리 옵니다.' },
    { voice: 'azortharion-iv', text: '연타하다 속사 정신 집중을 스스로 끊지 않도록 조준 사격·고정 사격 매크로에 [nochanneling:속사] 조건을 넣습니다. 일제 사격에는 넣지 않습니다.' },
  ],
  explosive: [
    { voice: 'azortharion-iv', text: '대상이 둘 이상이면 두 폭발 사격을 다른 대상에 나누는 편이 약간 이득입니다. 다만 우선 처치 대상이 있으면 나누지 않습니다. 쐐기 시간이 줄지 않는다고 8월 16일 변경 기록에 적었습니다.' },
    { voice: 'azortharion-videos', text: '폭발 사격을 너무 오래 아낀 것을 스스로 실수로 꼽습니다. 아주 짧게 맞추는 경우가 아니면 쿨다운마다 씁니다.' },
  ],
  single: [
    { voice: 'azortharion-iv', text: '전투 보조의 추천만 따라도 약 6~10%, 원버튼까지 쓰면 약 13~15% 손해라는 추정입니다. 처음엔 기대도 되지만 위 세 가지가 잡히면 손으로 옮겨 보세요.' },
    { voice: 'kr-inven', text: '상위권 로그는 속사를 쿨다운마다 쓰고, 조준 사격 뒤에는 신비한 사격·일제 사격·마무리 사격으로 정밀 사격을 소비한다는 정리가 인벤에 있습니다.' },
  ],
  aoe: [
    { voice: 'azortharion-iv', text: '광역에서는 조준 사격과 속사 뒤에 매번 일제 사격을 붙입니다. 정밀 사격 소비와 교묘한 사격 켜기를 한 번에 해결합니다.' },
    { voice: 'awoo', text: '연발 공격 6초 안에 속사와 조준 사격을 빨리 넣어야 합니다. 조준 사격 시전이 연발 공격이 끝난 뒤 끝나면 튕기지 않습니다.' },
    { voice: 'reddit-dps', text: '쐐기 로그의 시전 상위가 신비한 사격·고정 사격이라면 일제 사격이 부족하다는 신호입니다. 상위 로그는 일제 사격·조준 사격·속사 순이었습니다.' },
  ],
  movement: [
    { voice: 'azortharion-wh', text: '조준 사격을 시전하지 않는 시간에는 늘 조금이라도 좋은 자리로 움직입니다. 이동을 그 시간에 모아 두면 조준 사격이 끊기지 않습니다.' },
    { voice: 'azortharion-videos', text: '끝까지 시전할 자신이 없는 조준 사격은 시작하지 않습니다. 졸개가 곧 죽거나 바닥 효과를 피해야 하면 폭발 사격·연발 공격·속사로 넘어갑니다.' },
    { voice: 'azortharion-videos', text: '우두머리가 사라지기 직전에는 속사를 시작하지 않습니다. 다시 나타나면 조준 사격부터 쏴서 정신 집중이 끊기는 일을 피합니다.' },
  ],
  trueshot: [
    { voice: 'azortharion-iv', text: '정조준은 속사 바로 앞에 씁니다. 폭발 사격이 곧 돌아오면 정조준을 최대 15초까지 미루고, 마지막 정조준은 명중 30중첩에 맞춥니다.' },
    { voice: 'eggplant', text: '정조준 15초 안에는 폭발 사격을 넣을 자리가 거의 없습니다. 폭발 사격 두 번과 연발 공격을 먼저 넣고 정조준을 누릅니다.' },
    { voice: 'bansherz', text: '쐐기에서는 사격 지휘로 정조준을 1분 30초마다 쓰는 쪽을 선호합니다. 시뮬레이션으로는 또렷한 시야(2분)가 약간 앞서니 졸개가 나오는 주기를 보고 고릅니다.' },
  ],
  sentinel: [
    { voice: 'azortharion-iv', text: '정조준을 누르기 전에 표식이 없는 대상을 잡습니다. 깃털 분노가 현재 대상에 표식을 남기므로 이미 표식이 있으면 하나가 버려집니다.' },
    { voice: 'azortharion-iv', text: '달빛 회전 표창은 단일이면 정조준이 약 5초 남았을 때, 광역이면 끝나기 직전에 던집니다. 표창 피해가 늦게 들어가 7번 적중을 정조준 안에 넣기 위해서입니다.' },
    { voice: 'qenjua', text: '달빛 회전 표창은 사실상 공짜 실탄 장전이라 정조준 중 이동해야 할 때 요긴합니다.' },
    { voice: 'azortharion-videos', text: '우두머리가 둘이면 정조준과 속사를 서로 다른 우두머리에게 써서 표식 두 개를 만듭니다. 세 대상으로 늘리는 방법은 연습 없이 하면 오히려 손해라고 경고합니다.' },
  ],
  darkranger: [
    { voice: 'azortharion-sims', text: '9월 시뮬레이션에서 공격대 단일은 파수꾼 246.7K, 어둠 순찰자 220.5K입니다. 운영진 가이드는 "모든 콘텐츠에서 파수꾼"을 권합니다.' },
    { voice: 'eggplant', text: '어둠 순찰자 광역은 검은 화살 발동에 반응해야 해서 처음엔 어색합니다. 그래도 고른다면 발동을 쫓기 전에 교묘한 사격부터 확인합니다.' },
    { voice: 'stats', text: '10월 10일 집계에서 파수꾼 선택 비율은 신화 레이드 99.9%, 쐐기 상위 키 97.8%입니다. 어둠 순찰자는 취향으로 고르는 선택지에 가깝습니다.' },
  ],
  mythicplus: [
    { voice: 'azortharion-wh', text: '광역은 대상 수 상한이 있어 8명을 넘기면 효율이 크게 떨어진다고 봅니다. 큰 풀일수록 정조준 구간을 정확히 맞추는 것이 중요합니다.' },
    { voice: 'azortharion-videos', text: '고단 쐐기와 공격대 진행에서는 불굴을 찍습니다. 피해량 손해는 약 1%지만, 빼고 진행했다가 더 죽었다는 경험담이 있습니다.' },
  ],
  utility: [
    { voice: 'azortharion-iv', text: '자신에게 걸리는 시전이나 효과가 보이면 죽은 척하기로 지워 봅니다. 탱커가 죽으면 반사적으로 타르 덫을 깝니다.' },
    { voice: 'azortharion-videos', text: '거북의 상은 미리 정해 두는 생존기입니다. 쓰자마자 취소하는 매크로로 바로 공격에 복귀합니다. 차단은 늦지 않게 하고, 속사 정신 집중 중에도 손해 없이 쓸 수 있습니다.' },
    { voice: 'reddit-nalorakk', text: 'Den of Nalorakk의 어미 곰 격노는 새끼가 모두 죽은 뒤 평정의 사격으로 지웁니다. 새끼가 죽을 때마다 격노가 다시 쌓이기 때문입니다.' },
  ],
  advanced: [
    { voice: 'azortharion-iv', text: '8월 22일 변경 기록: 이제 속사 끝을 끊는 것은 파수꾼, 그것도 광역뿐입니다. 끊을 때는 마우스오버 일제 사격으로 파수꾼의 표식이 없는 대상을 칩니다.' },
    { voice: 'forum-unload', text: '단일에서는 속사 정신 집중을 끝까지 유지합니다. 끊기 운용은 세 대상 이상의 파수꾼 광역에서만 의미가 있습니다.' },
  ],
  logs: [
    { voice: 'reddit-logs', text: '취소된 조준 사격이 많은지, 조준 사격과 신비한 사격 시전 수가 비슷한지, 정조준 직후 빈 시간이 있는지부터 봅니다.' },
    { voice: 'kr-inven', text: '쿨기와 주요 스킬을 제때 못 쓴 것이 가장 큰 손실이었다는 이용자 사례가 있습니다. 세부 순서보다 사용 횟수가 먼저입니다.' },
  ],
};

const EXTRA_SOURCES = [
  {
    tier: 'B',
    label: 'Azortharion · 12.1 사냥꾼 시뮬레이션(트루샷 운영진)',
    url: 'https://azortharion.com/hunter-sims/',
    updated: '2026-09-19 갱신 / 2026-09-30 재계산 / 2026-10-10 확인',
    note: 'Trueshot Lodge 운영 책임자의 공개 시뮬레이션입니다. 파수꾼과 어둠 순찰자, 유동성 제동장치와 전술 재장전, 쐐기 광역 특성 비교를 현장의 목소리에 인용했습니다. 최상급 장비 가정 수치라 개인 결과로 단정하지 않습니다.',
  },
  {
    tier: 'A',
    label: 'Icy Veins · Azortharion 쐐기 팁',
    url: 'https://www.icy-veins.com/wow/marksmanship-hunter-pve-dps-mythic-plus-tips',
    updated: '2026-08-16 수정 / 2026-10-10 확인',
    note: '죽은 척하기 시전 해제, 탱커 사망 시 타르 덫, 정조준 구간 중심 운용 같은 쐐기 실전 팁을 확인했습니다. 같은 작성자의 다른 가이드와 독립 근거로 세지 않습니다.',
  },
  {
    tier: 'A',
    label: 'Icy Veins · Azortharion 매크로와 쉬운 운용',
    url: 'https://www.icy-veins.com/wow/marksmanship-hunter-pve-dps-macros-addons',
    updated: '2026-08-31 수정 / 2026-10-10 확인',
    note: '속사 정신 집중을 지키는 nochanneling 매크로와 일제 사격 예외, 거북의 상 즉시 취소 매크로를 확인했습니다. 전투 보조 손해 추정은 같은 사이트의 쉬운 운용 페이지 내용입니다.',
  },
  {
    tier: 'A',
    label: 'Wowhead · Azortharion 사격 쐐기 가이드',
    url: 'https://www.wowhead.com/ko/guide/classes/hunter/marksmanship/mythic-plus-dungeon-tips',
    updated: '2026-08-18 수정 / 2026-10-10 확인',
    note: '광역 대상 상한, 정조준 사이 낮은 피해, 던전별 평정의 사격·구속의 사격 대상을 확인했습니다. 브라우저로 읽었고 같은 작성자 자료로 묶어 셉니다.',
  },
  {
    tier: 'B',
    label: 'YouTube · Azortharion 레이드 1위 시점 해설',
    url: 'https://www.youtube.com/watch?v=lSh9qaa-nrA',
    updated: '2026-09-10 게시 / 2026-10-10 자막 확인',
    note: '쌍둥이 송곳니 해설 외 4편의 공개 자동 자막을 읽었습니다. 끝내지 못할 조준 사격 금지, 우두머리가 사라지기 전 속사 금지, 거북의 상 계획 사용 같은 실전 판단을 인용했습니다.',
  },
  {
    tier: 'B',
    label: 'YouTube · Bansherz 사격 특성과 딜사이클',
    url: 'https://www.youtube.com/watch?v=foRnDiuAC7E',
    updated: '2026-08-11 게시 / 2026-10-10 자막 확인',
    note: '고단 쐐기 사냥꾼의 12.1 시즌 2 영상입니다. 어둠 순찰자 비추천과 쐐기 정조준 주기 선택 의견을 인용했습니다. 공개 자동 자막 기준입니다.',
  },
  {
    tier: 'B',
    label: 'YouTube · Awoo 사냥꾼 종합(Bansherz 출연)',
    url: 'https://www.youtube.com/watch?v=LSKkSnwBtbs',
    updated: '2026-08-19 게시 / 2026-10-10 자막 확인',
    note: '사격 구간 자막을 읽었습니다. 광역에서 주력기와 일제 사격을 번갈아 쓰는 흐름, 연발 공격 6초 안의 시전 순서를 인용했습니다.',
  },
  {
    tier: 'B',
    label: 'YouTube · Mr. Eggplant 12.1 사격 가이드',
    url: 'https://www.youtube.com/watch?v=dJv1Hqmgq4Y',
    updated: '2026-08-18 게시 / 2026-10-10 자막 확인',
    note: '정조준 앞 폭발 사격 배치 이유와 영웅 특성 조작감 비교, 입문자용 전술 재장전 권장을 인용했습니다. 공개 자동 자막 기준입니다.',
  },
  {
    tier: 'C',
    label: 'Reddit r/CompetitiveWoW · 사격 로그 진단 토론',
    url: 'https://www.reddit.com/r/CompetitiveWoW/comments/1wbrqkk/from_mm_to_bm/',
    updated: '2026-09-09~09-13 / 2026-10-10 확인',
    note: '로그를 근거로 한 답변 위주로 읽었습니다. 조준 사격과 신비한 사격 시전 수 맞추기, 정조준 직후 공백, 시전 취소를 커뮤니티 의견으로 인용합니다.',
  },
  {
    tier: 'C',
    label: 'Reddit r/wow · 쐐기 피해량 상담',
    url: 'https://www.reddit.com/r/wow/comments/1wzcwv9/dps_problem/',
    updated: '2026-10-06 / 2026-10-10 확인',
    note: '상위 100위 로그와 시전 상위 3개를 비교한 답변을 읽었습니다. 쐐기 일제 사격 부족 진단을 커뮤니티 의견으로 인용합니다.',
  },
  {
    tier: 'C',
    label: 'Reddit r/CompetitiveWoW · Den of Nalorakk 평정의 사격',
    url: 'https://www.reddit.com/r/CompetitiveWoW/comments/1vtpckk/den_of_nalorakk_enraging_bears_when_am_i_suppose/',
    updated: '2026-08-20~08-30 / 2026-10-10 확인',
    note: '어미 곰 격노를 새끼가 모두 죽은 뒤 지우라는 추천 많은 답변을 인용합니다. 중첩 전부 해제 제보는 패치 노트에 없어 사용하지 않았습니다.',
  },
  {
    tier: 'C',
    label: 'Blizzard 포럼 · 사냥꾼 게시판 쏟아내기 토론',
    url: 'https://us.forums.blizzard.com/en/wow/t/unload-removed/2344932',
    updated: '2026-09-05 / 2026-10-10 확인',
    note: '라이브 단일에서는 속사를 끊지 않는다는 이용자 설명과 12.1.5 테스트 서버(PTR)의 쏟아내기 삭제 예고를 확인했습니다. 블루 답변이 아닌 이용자 의견입니다.',
  },
  {
    tier: 'B',
    label: 'murlok.io · 사격 쐐기 상위 50명',
    url: 'https://murlok.io/hunter/marksmanship/m+',
    updated: '2026-10-10 조회',
    note: '쐐기 상위 50명 중 49명이 파수꾼을 고른 집계를 확인했습니다. 선택 비율이며 같은 조건의 성능 비교가 아닙니다.',
  },
  {
    tier: 'C',
    label: 'YouTube · 금칩 12.1 격냥 딜사이클 가이드',
    url: 'https://www.youtube.com/watch?v=cFIoPWZehck',
    updated: '2026-08-26 게시 / 2026-10-10 확인',
    note: '한국 사냥꾼 영상입니다. 자막 접근이 막혀 제목·설명·챕터만 확인했고, 설명란의 단일 순서 간소화 언급만 현장의 목소리에 적었습니다.',
  },
  {
    tier: 'C',
    label: '인벤 · 와우 사냥꾼 게시판 12.1 격냥 글',
    url: 'https://www.inven.co.kr/board/wow/49/190224',
    updated: '2026-08-20~10-07 / 2026-10-10 확인',
    note: '격냥 딜사이클 정리 글과 표식·폭발 사격 질문 글의 본문을 읽었습니다. 댓글은 확인하지 못했고, 이용자 사례로만 인용합니다.',
  },
];

const TIPS = [
  '빈 글쿨이 가장 흔한 손실입니다. 레이드든 쐐기든 1초 고민하느니 틀린 스킬이라도 바로 쓰고, 이동 중에는 고정 사격으로 글쿨을 채우세요.',
  '조준 사격 직후에는 정밀 사격 소비를 한 번 붙입니다. 단, 조준 사격 바로 다음이 속사라면 쏟아내기가 정밀 사격을 가져가므로 소비를 끼우지 않습니다.',
  '끝까지 시전할 자신이 없는 조준 사격은 시작하지 마세요. 공격대 졸개가 곧 죽거나 바닥 효과를 피해야 하면 폭발 사격·연발 공격·속사로 넘어갑니다.',
  '정조준 직전에는 폭발 사격과 연발 공격을 먼저 넣고, 정조준 바로 다음에 속사를 씁니다. 폭발 사격이 곧 돌아오면 정조준을 최대 15초까지 미뤄도 됩니다.',
  '정조준을 누르기 전에 표식이 없는 대상을 잡으세요. 깃털 분노가 현재 대상에 표식을 남기므로 이미 표식이 있는 대상이면 하나가 버려집니다.',
  '쐐기 광역에서는 조준 사격과 속사 뒤에 매번 일제 사격을 붙여 정밀 사격 소비와 교묘한 사격 켜기를 한 번에 처리합니다. 로그 시전 상위가 신비한 사격이면 일제 사격이 부족한 신호입니다.',
  '쐐기에 우선 처치 대상이 있으면 폭발 사격 두 번을 그 대상에 씁니다. 나누면 총 피해만 약간 늘고 쐐기 시간은 줄지 않는다는 것이 공개 시뮬레이션의 결론입니다.',
  '파수꾼 단일에서는 속사 정신 집중을 끝까지 유지합니다. 속사 끝을 일제 사격으로 끊는 운용은 8월 20일 수정 이후 파수꾼 광역에서 표식을 퍼뜨릴 때만 이득입니다.',
  '공격대 우두머리가 사라지기 직전에는 속사를 시작하지 말고, 다시 나타나면 조준 사격부터 씁니다. 연발 공격은 졸개가 나오기 직전에 미리 깔아 둘 수 있습니다.',
  '탱커가 죽으면 반사적으로 타르 덫을 깔고, 자신에게 걸리는 시전이 보이면 죽은 척하기로 지워 보세요. 거북의 상은 미리 계획하고 쓰자마자 취소해 공격으로 돌아옵니다.',
];

const VOICES_INTRO = '가이드 작성자, 직업 디스코드 운영진, 상위 사냥꾼 영상, Reddit·공식 포럼, 한국 영상·인벤 글에서 12.1 적용 이후 자료를 모았습니다(2026-10-10 조사). 디스코드 대화는 로그인이 필요해 읽지 않았고, 운영진이 공개한 가이드·시뮬레이션·영상으로 대신했습니다. 영상은 공개 자동 자막을 읽은 것과 제목·설명만 본 것을 구분했고, 12.1.5 테스트 서버(PTR) 내용은 현재 서버 운용에 섞지 않았습니다.';

module.exports = { VOICES, FIELD_TIPS, EXTRA_SOURCES, TIPS, VOICES_INTRO };
