import fs from 'fs/promises';
import path from 'path';

/**
 * GuideGenerator - 데이터 파일 자동 생성기
 *
 * 검증된 데이터를 실제 파일로 생성
 * - specs/{className}/{specName}/ 폴더에 5개 파일 생성
 * - 일관된 포맷팅 및 주석
 * - 자동 생성 타임스탬프 포함
 */

export class GuideGenerator {
  constructor(className, specName, collectedData) {
    this.className = className;
    this.specName = specName;
    this.data = collectedData;
    this.outputDir = path.join(process.cwd(), 'src', 'specs', className, specName);
  }

  /**
   * 메인 생성 함수
   */
  async generate() {
    console.log(`\n📝 가이드 파일 생성 시작: ${this.className}/${this.specName}`);

    try {
      // 출력 디렉토리 생성
      await this.ensureDirectory();

      // 각 데이터 파일 생성
      console.log('  1/6 spec.config.js 생성 중...');
      await this.generateConfigFile();

      console.log('  2/6 rotation.data.js 생성 중...');
      await this.generateRotationFile();

      console.log('  3/6 talents.data.js 생성 중...');
      await this.generateTalentsFile();

      console.log('  4/6 stats.data.js 생성 중...');
      await this.generateStatsFile();

      console.log('  5/6 skills.auto.js 생성 중...');
      await this.generateSkillsFile();

      console.log('  6/6 index.js 생성 중...');
      await this.generateIndexFile();

      console.log(`\n✅ 가이드 데이터 생성 완료: ${this.outputDir}\n`);

    } catch (error) {
      console.error('❌ 파일 생성 실패:', error.message);
      throw error;
    }
  }

  /**
   * 디렉토리 생성 (재귀적)
   */
  async ensureDirectory() {
    await fs.mkdir(this.outputDir, { recursive: true });
  }

  /**
   * spec.config.js 생성
   */
  async generateConfigFile() {
    const { config } = this.data;
    const timestamp = new Date().toISOString();

    const content = `// Auto-generated by GuideGenerator
// Last updated: ${timestamp}
// Source: classMetadata + Wowhead

export const ${this.camelize(this.specName)}Config = ${JSON.stringify(config, null, 2)};

export default ${this.camelize(this.specName)}Config;
`;

    await fs.writeFile(path.join(this.outputDir, 'spec.config.js'), content, 'utf8');
  }

  /**
   * rotation.data.js 생성
   */
  async generateRotationFile() {
    const { rotation } = this.data;
    const timestamp = new Date().toISOString();

    const content = `// Auto-generated by GuideGenerator
// Last updated: ${timestamp}
// Source: Wowhead rotation guide

export const ${this.camelize(this.specName)}Rotation = ${JSON.stringify(rotation, null, 2)};

export default ${this.camelize(this.specName)}Rotation;
`;

    await fs.writeFile(path.join(this.outputDir, 'rotation.data.js'), content, 'utf8');
  }

  /**
   * talents.data.js 생성
   */
  async generateTalentsFile() {
    const { talents } = this.data;
    const timestamp = new Date().toISOString();

    const content = `// Auto-generated by GuideGenerator
// Last updated: ${timestamp}
// Source: Wowhead talent calculator

export const ${this.camelize(this.specName)}Talents = ${JSON.stringify(talents, null, 2)};

export default ${this.camelize(this.specName)}Talents;
`;

    await fs.writeFile(path.join(this.outputDir, 'talents.data.js'), content, 'utf8');
  }

  /**
   * stats.data.js 생성
   */
  async generateStatsFile() {
    const { stats } = this.data;
    const timestamp = new Date().toISOString();

    const content = `// Auto-generated by GuideGenerator
// Last updated: ${timestamp}
// Source: Maxroll stat priority

export const ${this.camelize(this.specName)}Stats = ${JSON.stringify(stats, null, 2)};

export default ${this.camelize(this.specName)}Stats;
`;

    await fs.writeFile(path.join(this.outputDir, 'stats.data.js'), content, 'utf8');
  }

  /**
   * skills.auto.js 생성
   */
  async generateSkillsFile() {
    const { skills } = this.data;
    const skillIds = Object.keys(skills);
    const timestamp = new Date().toISOString();

    // 스킬 데이터를 직접 내장 (masterDB 참조 방식은 나중에 최적화 가능)
    const content = `// Auto-generated by GuideGenerator
// Last updated: ${timestamp}
// Skills used in ${this.className} ${this.specName}
// Total: ${skillIds.length} skills

export const ${this.camelize(this.specName)}Skills = ${JSON.stringify(skills, null, 2)};

export default ${this.camelize(this.specName)}Skills;
`;

    await fs.writeFile(path.join(this.outputDir, 'skills.auto.js'), content, 'utf8');
  }

  /**
   * index.js 생성 (통합 export)
   */
  async generateIndexFile() {
    const camelSpec = this.camelize(this.specName);

    const content = `// Auto-generated by GuideGenerator
// Centralized export for ${this.className} ${this.specName}

export { ${camelSpec}Config } from './spec.config.js';
export { ${camelSpec}Rotation } from './rotation.data.js';
export { ${camelSpec}Talents } from './talents.data.js';
export { ${camelSpec}Stats } from './stats.data.js';
export { ${camelSpec}Skills } from './skills.auto.js';

// 통합 객체로도 export
export const ${camelSpec}Data = {
  config: null,  // lazy load
  rotation: null,
  talents: null,
  stats: null,
  skills: null
};

// 지연 로딩 함수
export async function load${this.capitalize(camelSpec)}Data() {
  if (!${camelSpec}Data.config) {
    const config = await import('./spec.config.js');
    const rotation = await import('./rotation.data.js');
    const talents = await import('./talents.data.js');
    const stats = await import('./stats.data.js');
    const skills = await import('./skills.auto.js');

    ${camelSpec}Data.config = config.default;
    ${camelSpec}Data.rotation = rotation.default;
    ${camelSpec}Data.talents = talents.default;
    ${camelSpec}Data.stats = stats.default;
    ${camelSpec}Data.skills = skills.default;
  }

  return ${camelSpec}Data;
}
`;

    await fs.writeFile(path.join(this.outputDir, 'index.js'), content, 'utf8');
  }

  /**
   * 유틸리티 함수
   */

  /**
   * camelCase로 변환 (예: "beast-mastery" → "beastMastery")
   */
  camelize(str) {
    return str
      .replace(/(?:^\w|[A-Z]|\b\w)/g, (word, index) => {
        return index === 0 ? word.toLowerCase() : word.toUpperCase();
      })
      .replace(/\s+|-+/g, '');
  }

  /**
   * 첫 글자 대문자 (예: "arcane" → "Arcane")
   */
  capitalize(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}

/**
 * App.js 라우팅 자동 추가
 */
export class AppRouter {
  constructor(className, specName) {
    this.className = className;
    this.specName = specName;
    this.appJsPath = path.join(process.cwd(), 'src', 'App.js');
  }

  /**
   * App.js에 라우트 추가
   */
  async addRoute() {
    console.log('\n🔗 App.js 라우팅 추가 중...');

    try {
      // App.js 읽기
      const appJsContent = await fs.readFile(this.appJsPath, 'utf8');

      // 이미 라우트가 있는지 확인
      const routePath = `/guide/${this.className}/${this.specName}`;
      if (appJsContent.includes(routePath)) {
        console.log(`  ⚠️  라우트 이미 존재: ${routePath}`);
        return;
      }

      // TODO: App.js에 라우트 자동 추가 로직
      // 현재는 수동 추가 필요 (복잡한 파싱 필요)
      console.log(`  ℹ️  수동 추가 필요: ${routePath}`);
      console.log(`     다음 코드를 App.js에 추가하세요:`);
      console.log(`
import GuideRenderer from './components/GuideRenderer.js';
import { load${this.capitalize(this.camelize(this.specName))}Data } from './specs/${this.className}/${this.specName}.js';

// Route 추가:
<Route
  path="${routePath}"
  element={<GuideRenderer specData={await load${this.capitalize(this.camelize(this.specName))}Data()} />}
/>
`);

    } catch (error) {
      console.error('❌ 라우팅 추가 실패:', error.message);
    }
  }

  camelize(str) {
    return str
      .replace(/(?:^\w|[A-Z]|\b\w)/g, (word, index) => {
        return index === 0 ? word.toLowerCase() : word.toUpperCase();
      })
      .replace(/\s+|-+/g, '');
  }

  capitalize(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}

export default GuideGenerator;
